from crewai import Agent
from crewai.llm import LLM
from crewai_tools import FileReadTool, FileWriterTool

# Tools for reading and rewriting code files
file_reader = FileReadTool()
file_writer = FileWriterTool(result_as_answer=True)

code_enhancer_agent = Agent(
    role="Senior Code Reviewer and Enhancer",
    goal=(
        "Review existing frontend and backend code and enhance it "
        "for quality, performance, security, and best practices."
    ),
    backstory=(
        "You are a senior software engineer with 10+ years of experience.\n"
        "You receive code generated by frontend and backend agents.\n"
        "You MUST read existing files using FileReadTool.\n"
        "You MUST refactor and improve the SAME files using FileWriterTool.\n"
        "You MUST NOT change the application functionality.\n"
        "You MUST NOT execute code.\n"
        "You MUST NOT explain anything in the output.\n"
        "ONLY enhanced production-ready code is written back to files."
    ),
    tools=[file_reader, file_writer],
    llm=LLM(
        model="ollama/qwen3-coder:480b-cloud",
        base_url="http://localhost:11434"
    ),
    allow_code_execution=False,
    max_iter=15,
    verbose=True
)

print(" Code Enhancer Agent initialized successfully")
